"""add_product_batches

Revision ID: 46e6b0bcf412
Revises: 57956aeb638e
Create Date: 2026-03-10 22:47:45.759025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46e6b0bcf412'
down_revision: Union[str, None] = '57956aeb638e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=False),
    sa.Column('initial_quantity', sa.Integer(), nullable=False),
    sa.Column('current_quantity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_batches_product_expiration', 'product_batches', ['product_id', 'expiration_date'], unique=False)
    op.create_index('idx_batches_tenant_active', 'product_batches', ['tenant_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_product_batches_id'), 'product_batches', ['id'], unique=False)
    op.create_index(op.f('ix_product_batches_product_id'), 'product_batches', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_batches_tenant_id'), 'product_batches', ['tenant_id'], unique=False)
    op.add_column('sale_items', sa.Column('batch_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_sale_items_batch_id'), 'sale_items', ['batch_id'], unique=False)
    op.create_foreign_key(None, 'sale_items', 'product_batches', ['batch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sale_items', type_='foreignkey')
    op.drop_index(op.f('ix_sale_items_batch_id'), table_name='sale_items')
    op.drop_column('sale_items', 'batch_id')
    op.drop_index(op.f('ix_product_batches_tenant_id'), table_name='product_batches')
    op.drop_index(op.f('ix_product_batches_product_id'), table_name='product_batches')
    op.drop_index(op.f('ix_product_batches_id'), table_name='product_batches')
    op.drop_index('idx_batches_tenant_active', table_name='product_batches')
    op.drop_index('idx_batches_product_expiration', table_name='product_batches')
    op.drop_table('product_batches')
    # ### end Alembic commands ###
