"""add_batch_id_to_inventory_movements

Revision ID: 59f7cb5839b5
Revises: 46e6b0bcf412
Create Date: 2026-03-10 22:49:23.571265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59f7cb5839b5'
down_revision: Union[str, None] = '46e6b0bcf412'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_movements', sa.Column('batch_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_inventory_movements_batch_id'), 'inventory_movements', ['batch_id'], unique=False)
    op.create_foreign_key(None, 'inventory_movements', 'product_batches', ['batch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory_movements', type_='foreignkey')
    op.drop_index(op.f('ix_inventory_movements_batch_id'), table_name='inventory_movements')
    op.drop_column('inventory_movements', 'batch_id')
    # ### end Alembic commands ###
