"""add payment tracking to purchases

Revision ID: 78e784b0c177
Revises: 
Create Date: 2026-03-06 22:54:50.347004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78e784b0c177'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.create_index('idx_categories_tenant_active', 'categories', ['tenant_id', 'is_active'], unique=False)
    op.drop_constraint('permissions_codename_key', 'permissions', type_='unique')
    op.create_index(op.f('ix_permissions_codename'), 'permissions', ['codename'], unique=True)
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.drop_constraint('purchase_items_purchase_id_fkey', 'purchase_items', type_='foreignkey')
    op.create_foreign_key(None, 'purchase_items', 'purchases', ['purchase_id'], ['id'], ondelete='CASCADE')
    op.add_column('purchases', sa.Column('payment_status', sa.Enum('PENDING', 'PARTIAL', 'PAID', name='purchasepaymentstatus'), nullable=True))
    op.execute("UPDATE purchases SET payment_status = 'PENDING' WHERE payment_status IS NULL")
    op.alter_column('purchases', 'payment_status', nullable=False)
    op.add_column('purchases', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.alter_column('roles', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('roles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.alter_column('sales', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'completed'::character varying"))
    op.create_index(op.f('ix_sales_customer_id'), 'sales', ['customer_id'], unique=False)
    op.execute("ALTER TABLE users ALTER COLUMN role DROP DEFAULT")
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('SUPERADMIN', 'ADMIN', 'MANAGER', 'SELLER', name='userrole'),
               nullable=False,
               postgresql_using='UPPER(role)::userrole')
    op.execute("ALTER TABLE users ALTER COLUMN role SET DEFAULT 'SELLER'::userrole")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('SUPERADMIN', 'ADMIN', 'MANAGER', 'SELLER', name='userrole'),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'seller'::character varying"))
    op.drop_index(op.f('ix_sales_customer_id'), table_name='sales')
    op.alter_column('sales', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'completed'::character varying"))
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.alter_column('roles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('roles', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('purchases', 'due_date')
    op.drop_column('purchases', 'payment_status')
    op.drop_constraint(None, 'purchase_items', type_='foreignkey')
    op.create_foreign_key('purchase_items_purchase_id_fkey', 'purchase_items', 'purchases', ['purchase_id'], ['id'])
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_codename'), table_name='permissions')
    op.create_unique_constraint('permissions_codename_key', 'permissions', ['codename'])
    op.drop_index('idx_categories_tenant_active', table_name='categories')
    op.alter_column('categories', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###
